# CodeRabbit Configuration
# https://docs.coderabbit.ai/configuration

language: en-US

reviews:
  # Auto-review PRs
  auto_review:
    enabled: true
    drafts: false
    base_branches:
      - main
      - develop

  # Review profile: chill = fewer nitpicks, assertive = more thorough
  profile: chill

  # Request changes on high severity issues
  request_changes_workflow: true

  # High-level summary at the top of review
  high_level_summary: true

  # Add poem to review (fun touch)
  poem: false

  # Review hints
  review_status: true

  # Collapse walkthrough in collapsible section
  collapse_walkthrough: true

  # Path-based instructions
  path_instructions:
    - path: "src/**/*.ts"
      instructions: |
        - Check for command injection vulnerabilities (avoid exec with string interpolation)
        - Ensure proper error handling with CLIError
        - Verify TypeScript strict mode compliance
    - path: "tests/**/*.ts"
      instructions: |
        - Verify tests cover edge cases
        - Check for proper async/await handling

  # Files to ignore
  path_filters:
    - "!**/pnpm-lock.yaml"
    - "!**/dist/**"
    - "!**/*.map"

# Chat settings
chat:
  auto_reply: true

# Early access features
early_access: false
